import aiogram

# Кнопка меню
button_forgotten = aiogram.types.KeyboardButton(text="Забуті місця Києва")
button_cafe = aiogram.types.KeyboardButton(text="Поїсти")
button_nature = aiogram.types.KeyboardButton(text='Відпочинок на природі')
button_active = aiogram.types.KeyboardButton(text='Активний відпочинок')
button_donat = aiogram.types.KeyboardButton(text='Підтримати продукт')
button_panoramic = aiogram.types.KeyboardButton(text='Панорамний вид')
button_areas = aiogram.types.KeyboardButton(text='Площі')
button_hotels = aiogram.types.KeyboardButton(text='Готелі')
button_museums = aiogram.types.KeyboardButton(text='Музеї')
button_cathedrals = aiogram.types.KeyboardButton(text='Церкви, собори, монастирі')
button_historical_monument = aiogram.types.KeyboardButton(text="Історичні пам'ятки")
button_other = aiogram.types.KeyboardButton(text='Інше')
button_search_metro = aiogram.types.KeyboardButton(text='Пошук по метро')
button_next = aiogram.types.KeyboardButton(text='▶️')
button_next1 = aiogram.types.KeyboardButton(text='🔜')
button_back = aiogram.types.KeyboardButton(text='◀️')
button_back1 = aiogram.types.KeyboardButton(text='🔙')
